a, b=input().split()
add= int(a)+int(b)
sub= int(a)-int(b)
multi= int(a)*int(b)
div= int(a)//int(b)
div2= int(a)%int(b)
div_r=int(a)/int(b)
print(add)
print(sub)
print(multi)
print(div)
print(div2)
print(format(div_r,'.2f'))